# fonts/fonts.toml
module = "icon"

[glyphs]
home = "fontawesome-home"
global = "fontawesome-globe"
cog = "fontawesome-cog"
edit = "fontawesome-pencil"
trash = "fontawesome-trash"
plus = "fontawesome-plus"
swap = "fontawesome-exchange"
copy = "fontawesome-docs"
code = "fontawesome-file-code"
theme = "typicons-brush"
preview = "fontawesome-picture"